spring:
  application:
    name: apipxkiengiang
  jmx:
    default-domain: apitccc
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.hostname}:${db.port}/${db.schema}?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${db.username}
    password: ${db.password}
    initial-size: 100
    max-active: 500
    max-idle: 5
    max-wait: 1000
    min-idle: 1
    min-evictable-idle-time-millis: 34000
    time-between-eviction-runs-millis: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      format-sql: true
  profiles:
    active: prod

info:
  component: This is REST API for Notarial Services.

server:
  port: 8082
  contextPath: /apitccchgi/
  address: 0.0.0.0

hystrix:
  streamEnabled: true
  enabled: true

archaius:
  dynamicPropertyFactory:
    registerConfigWithJMX: true

endpoints:
    jmx:
      domain: apitccc
      unique-names: true
    restart:
      enabled: true

oauth:
  resourceId: service-service
  clientId: 4f7ec648a48b9d3fa239b497f7b6b4d8019697bd
  clientSecret: edfeba07ec1dd4ff45928ee715a8e1ecc149a060
  tokenEndpoint: http://${oauth.hostname}:8080/oauth/check_token
  authzEndpoint: http://${oauth.hostname}:8080/oauth/authorize

logging:
   levels:
    # org.springframework.boot.env.PropertySourcesLoader: TRACE

     org.springframework.web: ERROR
     com.vn.osp.notarialservices.transaction.controller: DEBUG
   pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
     file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
   file: /OSP/projects/logs/debug.log
http:
    multipart:
        max-file-size: 5MB
        max-request-size: 5MB